### PR TITLE
Task 3 (Xinyuan)

### PR DESCRIPTION
**Pull request by AnLuoRidge**
# Last challenge
I've completed most of the challenges, but still cannot solve the last one.

I tried to override the `expanded` class in `ExpansionPanel` and `ExpansionPanelSummary`. The new class was injected but didn't replace the original `expanded` class. To figure out what's happening, I wrote a [demo](https://codesandbox.io/s/0376n9050?fontsize=14) with `ExpansionPanel` related components. It partially worked with no spacing between panels.

 I guess my injection of the `expanded` class was too late, but don't know how to approve that.

# Colour
- The top bar should be purple, but my one is lighter than that.  Still, I haven't figured out why.
- I failed to set the text colour of the chips. Instead, I set the detail panel’s colour to `primary`.

### CODE REVIEW

**Comment by notsidney** [comment]
This task was designed to see how well you could read through the documentation.
Here are some explanations of how to solve it:

## Top bar colour
If the primary colour were set to deepPurple and the secondary to pink in the theme, and the top bar was set to use the primary colour, it would have produced the right colour.

By default, Material-UI defaults to the A400 shade for secondary colours, which is much brighter (to follow Google’s Material Design guidelines). You can see this here in the colour tool: https://next.material-ui.com/customization/color/#color-tool

## Chip colour
The `ExpansionPanelDetails` component doesn’t actually have a `color` prop, so setting it did nothing. There’s a list of props on its API page: https://next.material-ui.com/api/expansion-panel-details/

All I did to style the `Chip` was set the `variant` to `outlined`, which also changes its text colour. There’s also a handy playground on its demo page: https://next.material-ui.com/components/chips/#chip-playground

## Chip spacing
While your solution to add right and bottom margins to the chips definitely works, it might not be the best solution. For example, if a row of chips were perfectly sized to fit in their container’s width, excluding the right margin of the last chip, it would flow on to the next row and leave a big gap. Consider keeping the margin of the chip symmetrical and use a negative margin on the container to counteract the extra spacing it would produce.

## ExpansionPanel
Your custom styles for the panel’s expanded state were being overridden by the default styles:
image
The fastest way to solve that is to use `!important` in your CSS style.

A better way to have done this altogether is to use overrides in the theme and styling just the `root` class of the component. Here’s some explanation in the docs:
* https://next.material-ui.com/customization/globals/
* https://next.material-ui.com/customization/components/#use-rulename-to-reference-a-local-rule-within-the-same-style-sheet

To be fair, it took me quite a while to find this info when I was first using this library and to figure out that this was the right solution, so that’s why this is marked as the hard challenge.

## Note on Material-UI’s different styling APIs
The library provides three different styling APIs (hook, styled components, HOC) – it would be better if you stuck with just one of them throughout the whole app.

- - -

Overall, this is a good attempt. Don’t worry too much about the harder challenges since they test how well you can use this specific library (assuming) without much experience with it. Your CSS knowledge seems solid and the demo and investigation you provided showed great initiative.

**Comment by AnLuoRidge** [comment]
Thank you for your detailed explanation! Now the page looks much better after I took up your suggestions. I realised I didn't read the material-ui doc carefully.

Plus, I tried different styles around in previous commits. Now, I decided to employ the hook style. Even though I like the styled component most, it doesn’t support all kinds of styling.

So far, there's only one problem left. How to remove the 8px top margin of chips in the first line? They look so nice in the task sheet.




PS: To apply the negative margin only to the last panel, I passed the style into the Panel component in `App.js`. Is it a good idea?

**Comment by notsidney** [comment]
## Chip spacing
In `App.js`, you already set `margin: 'auto -4px'` for `ExpansionPanelDetails`. All you had to do from here was set `-4px` for all 4 directions (currently it is only for left & right).

## Where to put styles
For the styles for the `Panel` component, it looked like you were trying to pass in a class (`classes.expansionPanelDetails`) to override the default styles of the `Panel` component. This is fine and is the same way MUI handles this (except it takes in the `classes` prop, which is an object, so it would be like `classes={{ detailPanelStyle: classes.expansionPanelDetails }}`).

However, be careful with how far up you put your styles. Since you put it in `App.js`, the theme is not accessible to the styles you passed, since the theme is only accessible to the child components of `App`, because that’s where the `MuiThemeProvider` is.

Also, instead of passing in overrides this way, you could have just styled the `ChipArray` component with the negative margin instead.

## Note on MUI props vs CSS
Also note that props in MUI components cannot be changed in JSS styles. In `App.js` line 36 you had `maxWidth: 'md',` – this is correct as a prop to the `Container` element, but since JSS translates into CSS, the HTML component will receive `maxWidth: md`, which is invalid.

If you wanted to access the theme’s breakpoints from your JSS, you would need to pass in a function that takes a `theme` and returns an object into `makeStyles`, then use `theme.breakpoints.width('md')` to access the width value. `theme.breakpoints.width()` is not really documented, but you can view all the helper functions in MUI themes here: https://next.material-ui.com/customization/default-theme/

You might have been thinking of default props in theme overrides, where you *can* change default props for components in what looks like JSS, but that is only for the theme object itself, not when creating styles for specific components: https://next.material-ui.com/customization/globals/#default-props

**Comment by AnLuoRidge** [comment]
## Chip spacing
Finally, I removed the gap by styling in the `ChipArray` component.

## Where to put styles
Yes, you are right, and I forgot to style in the `ChipArray` component. Styling in `App.js` is not a good idea.

## Note on MUI props vs CSS
Oh, yes, I did mix the props and CSS attributes in MUI. I even set `color` to `primary` in CSS once 😥. The explanation of the breakpoint in theme really helps, so as the default props in the theme.

Thank you so much!

**Pull request closed without merging**
